"""Turns the three CyberKnight reference renders into animation-ready cut-out layers.

Input: background-removed RGBA cut-outs of the client's reference images (BiRefNet via rembg:
  `rembg i -m birefnet-general ref.jpg cut.png`), named A (arms crossed), B (hand on chest),
  C (palm up, three-quarter shot).
Output (assets/knight/): per pose
  <P>.png        the armour, trimmed and padded
  <P>_glow.png   the red neon seams below the helmet, pre-bloomed (screen-blended and pulsed at runtime)
  <P>_visor.png  the helmet's neon only (flickers when the knight speaks, dims when he blinks)
  poses.js       pixel geometry: image size, feet anchor, figure height
Usage: python3 tools/prep_knights.py A=cutA.png B=cutB.png C=cutC.png
"""
import json, os, sys
import numpy as np
import cv2
from PIL import Image, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "assets", "knight")
PAD = 56
# helmet height as a fraction of the visible figure; C is a three-quarter shot cropped mid-thigh,
# so its full-body height is extrapolated from the visible part
HEAD = {"A": 0.17, "B": 0.17, "C": 0.27}
VISIBLE = {"A": 1.0, "B": 1.0, "C": 0.62}
# hologram lettering that bled onto C's shoulder in the source art (x0, y0, x1, y1 in source px)
SCRUB = {"C": [(1150, 405, 1240, 560), (1150, 625, 1205, 668)]}


def neon(rgb, a):
    r, g, b = [rgb[..., i].astype(np.float32) for i in range(3)]
    m = np.clip((r - 1.35 * np.maximum(g, b) - 18) / 90, 0, 1) * np.clip((r - 80) / 90, 0, 1) * (a / 255.0)
    return m


def bloom(m):
    im = Image.fromarray((m * 255).astype(np.uint8))
    b1 = np.asarray(im.filter(ImageFilter.GaussianBlur(5)), np.float32) / 255
    b2 = np.asarray(im.filter(ImageFilter.GaussianBlur(16)), np.float32) / 255
    return np.clip(m * 1.0 + b1 * 0.9 + b2 * 0.9, 0, 1)


def layer(m, rgb):
    # emissive colour: the source red pushed hotter where the seam is brightest
    col = np.zeros(rgb.shape, np.float32)
    col[..., 0] = 255
    col[..., 1] = 40 + 150 * np.clip(m - 0.55, 0, 1)
    col[..., 2] = 60 + 150 * np.clip(m - 0.55, 0, 1)
    return Image.fromarray(np.dstack([col, m * 255]).astype(np.uint8), "RGBA")


def main(args):
    os.makedirs(OUT, exist_ok=True)
    meta = {}
    for arg in args:
        key, path = arg.split("=", 1)
        src = np.asarray(Image.open(path).convert("RGBA")).copy()
        for x0, y0, x1, y1 in SCRUB.get(key, []):
            box = src[y0:y1, x0:x1, :3].copy()
            lum = box.mean(axis=2)
            mask = ((lum > 150) & (box[..., 1] > 110)).astype(np.uint8) * 255
            mask = cv2.dilate(mask, np.ones((5, 5), np.uint8))
            fixed = cv2.inpaint(np.ascontiguousarray(box[..., ::-1]), mask, 6, cv2.INPAINT_TELEA)[..., ::-1]
            src[y0:y1, x0:x1, :3] = fixed
        a = src[..., 3]
        a[a < 12] = 0
        ys, xs = np.nonzero(a)
        x0, x1, y0, y1 = xs.min(), xs.max() + 1, ys.min(), ys.max() + 1
        crop = np.zeros((y1 - y0 + 2 * PAD, x1 - x0 + 2 * PAD, 4), np.uint8)
        crop[PAD:-PAD, PAD:-PAD] = src[y0:y1, x0:x1]
        rgb, al = crop[..., :3], crop[..., 3]
        H, W = al.shape
        fig_h = y1 - y0
        # feet anchor: alpha centroid of the bottom 6 % (full-body poses); C anchors on its visible centre line
        if VISIBLE[key] >= 1:
            band = al[PAD + int(fig_h * 0.94): PAD + fig_h]
            cols = np.nonzero(band.sum(axis=0))[0]
            ax = float(cols.mean())
        else:
            ax = float(np.nonzero(al.sum(axis=0))[0].mean())
        full_h = fig_h / VISIBLE[key]
        ay = PAD + full_h
        head_y = PAD + int(fig_h * HEAD[key])
        m = neon(rgb, al)
        body_m, head_m = m.copy(), m.copy()
        body_m[:head_y] = 0
        head_m[head_y:] = 0
        Image.fromarray(crop, "RGBA").save(os.path.join(OUT, f"{key}.png"), optimize=True)
        layer(bloom(body_m), rgb).save(os.path.join(OUT, f"{key}_glow.png"), optimize=True)
        layer(bloom(head_m), rgb).save(os.path.join(OUT, f"{key}_visor.png"), optimize=True)
        meta[key] = {"w": W, "h": H, "ax": round(ax, 1), "ay": round(ay, 1), "top": PAD, "figH": round(full_h, 1), "headY": head_y}
        print(key, meta[key])
    with open(os.path.join(OUT, "poses.js"), "w") as f:
        f.write("// generated by tools/prep_knights.py: cut-out geometry in source pixels\nexport default " + json.dumps(meta, indent=1) + ";\n")


if __name__ == "__main__":
    main(sys.argv[1:])
